export const MAX_CATEGORY_COUNT = 10;

export const MAX_CATEGORY_NAME_LENGTH = 6;
export const MAX_CATEGORY_NAME_LENGTH_ERROR = `分类名称最多 ${MAX_CATEGORY_NAME_LENGTH} 个字`;

export const MAX_CATEGORY_MATCH_LENGTH = 100;
export const MAX_CATEGORY_MATCH_LENGTH_ERROR = `匹配关键字最多 ${MAX_CATEGORY_MATCH_LENGTH} 个字`;
